<p>Hyun C</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><strong>Professional Summary</strong></p>
<p>I am a motivated and adaptable professional with a background in health communication, research, and technology. I bring experience in data-driven analysis, geospatial tools, and intelligence-relevant skill sets, developed through fellowships, public health work, and technical training in cybersecurity and Python. My commitment to public service and national security drives my interest in applying analytical and geospatial methods to support timely, accurate decision-making in a dynamic environment.</p>
<h2><strong>Skills</strong></h2>
<ul>
<li></li>
<li><strong>Programming &amp; Technical:</strong> Python scripting, cloud computing, virtualization, cybersecurity lab development</li>
<li><strong>Languages:</strong> Proficient in English, Spanish, and Korean</li>
<li><strong>Analysis &amp; Research:</strong> Open-source intelligence (OSINT), data visualization, primary literature review</li>
<li><strong>Communication:</strong> Writing, editing, presenting complex information clearly</li>
</ul>
<h2><strong>Relevant Experience</strong></h2>
<h3><strong>Innovations Fellow</strong></h3>
<p><strong>The Knowledge House</strong>&nbsp; | Jan 2025 &ndash; Present</p>
<ul>
<li>Completed an intensive fellowship in cybersecurity, Python, Linux, AWS, and cloud computing, with a focus on solving challenges in underserved communities.</li>
<li>Designed and implemented a home cybersecurity lab, simulating real-world attacks and defenses for critical infrastructure.</li>
<li>Developed proficiency in artificial intelligence tools for enhanced cybersecurity operations.</li>
<li>Contributed to scripting and produced a professional video demo that showcased the solutions for the Capture the Flag competition.</li>
<li>Strengthened teamwork, problem-solving, and technical presentation skills in a high-pressure, collaborative environment.</li>
</ul>
<p><strong>Grow with Google Scholar</strong></p>
<p><strong>Arts &amp; Humanities Council</strong>&nbsp; | Jan 2025 &ndash; Present</p>
<ul>
<li>Earned certificates in Cybersecurity and IT Support, learning about network security and system administration.</li>
<li>Gained proficiency in artificial intelligence tools</li>
</ul>
<h3><strong>Communications Fellow</strong></h3>
<p><strong>National Cancer Institute (NCI)</strong>, Rockville, MD | Jun 2022 &ndash; Jun 2023</p>
<ul>
<li>Collected and analyzed user data from digital platforms to improve communication strategies.</li>
<li>Created and managed content for social media campaigns, podcasts, and webinars with a focus on data-driven insights and inclusion.</li>
<li>Reviewed and synthesized over 900 research abstracts on health disparities for policymaker outreach.</li>
<li>Proposed and piloted new platforms to improve engagement metrics in target populations.</li>
</ul>
<h3><strong>Health Policy Research Intern</strong></h3>
<p><strong>Charles R. Drew University</strong>, Los Angeles, CA | Jan 2019 &ndash; Jun 2019</p>
<ul>
<li>Researched and drafted policy briefs summarizing health disparities and their implications for strategic planning.</li>
<li>Conducted literature reviews and data analysis to inform public health priorities in Los Angeles County.</li>
</ul>
<h3><strong>Research Assistant, Cancer Division</strong></h3>
<p><strong>Charles R. Drew University</strong>, Los Angeles, CA | Sep 2017 &ndash; Aug 2018</p>
<ul>
<li>Assisted in laboratory and computational research examining HPV and cervical cancer pathways.</li>
<li>Contributed to presentations and abstracts accepted by the American Association for Cancer Research.</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Education</strong></h2>
<p><strong>Los Angeles City College</strong><br /> Machine Learning</p>
<p>&nbsp;</p>
<h2><strong>Honors &amp; Awards</strong></h2>
<ul>
<li>Pipeline Program Scholarship, Wells Fargo Grant, 2018</li>
<li>Frank McMillan Stewart Foundation Scholarship, 2018</li>
<li>Society of Professional Journalists &ndash; National 1st Place, Editorial Writing, 2012</li>
</ul>
<p>&nbsp;</p>
<h2><strong>Community Service</strong></h2>
<ul>
<li>Volunteer writer, NIH Catalyst, 2023</li>
<li>Science education volunteer, Kid Museum, 2024&ndash;present</li>
<li>English tutor for refugee clients, Lutheran Social Services, 2024&ndash;present</li>
<li>Hospice patient support, Jewish Social Services Agency, 2024&ndash;present</li>
</ul>
